### ISSUE TITLE
Problem loading data with fractional time stamps

### ISSUE THREAD

**Issue by srp-synengco** [Synergetic-Engineering/odata-influxdb#12]
Influx allows for time stamps down to the nano second

So far, we've just been rounding our data for ease of use, but when I tried loading up some data with the very precise time, there was an error in the server

I've created a measure `IssueWithFractionalTimeStamps` in our dev influxdb that 

```
Traceback (most recent call last):
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\odata2\server.py", line 328, in __call__
    request, environ, start_response, response_headers)
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\odata2\server.py", line 1547, in HandleRequest
    request, environ, start_response, response_headers)
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\odata2\server.py", line 773, in HandleRequest
    response_headers)
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\odata2\server.py", line 1113, in ReturnEntityCollection
    data = str(doc)
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\xml20081126\structures.py", line 347, in __str__
    self.WriteXML(s, EscapeCharData7)
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\xml20081126\structures.py", line 548, in WriteXML
    for s in self.GenerateXML(escapeFunction, tab):
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\xml20081126\structures.py", line 544, in GenerateXML
    for s in self.root.GenerateXML(escapeFunction, '', tab, root=True):
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\xmlnames20091208.py", line 376, in GenerateXML
    child = children.next()
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\xml20081126\structures.py", line 1581, in GetCanonicalChildren
    iChild = children.next()
  File "C:\Projects\soundstripe\odata-influxdb\env\lib\site-packages\pyslet\odata2\core.py", line 3255, in GetChildren
    for entity in self.collection.iterpage():
  File "C:\Projects\soundstripe\odata-influxdb\influxdbds.py", line 211, in iterpage
    for e in self.itervalues():
  File "C:\Projects\soundstripe\odata-influxdb\influxdbds.py", line 106, in expand_entities
    for e in entityIterable:
  File "C:\Projects\soundstripe\odata-influxdb\influxdbds.py", line 129, in _generate_entities
    t = datetime.datetime.strptime(m['time'], '%Y-%m-%dT%H:%M:%SZ')
  File "c:\anaconda2\Lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2017-05-08T23:09:47.685131794Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

Guessing it'll just be a matter of adding to that line 129 in `influxdbds.py`: `t = datetime.datetime.strptime(m['time'], '%Y-%m-%dT%H:%M:%SZ')`, but worth adding a test into the suite for

note: not sure if the term 'fractional time stamp' is very correct

**Comment by soundstripe** [comment]
The simplest fix for this would be to parse it correctly, but the `datetime` type in python is limited to microsecond accuracy, which in this case would truncate 3 decimals from the timestamp when passing it through this service. For the applications I've seen so far, this would probably be acceptable.

A more complex fix would be to split the field into two fields or a "Complex" type field which has two parts: 1) the `datetime` with microsecond accuracy plus 2) the remaining digits, or a `Double` representing the timestamp in seconds.

I'll proceed with the simple way for now--should be a pretty easy fix.

**Comment by srp-synengco** [comment]
have tested #13 on the example in dev influxdb and it's all good now
