### ISSUE TITLE
Methods renamed in pyslet.odata2.client and influxdb.client

### ISSUE THREAD

**Issue by OzymandiasII** [Synergetic-Engineering/odata-influxdb#22]
Hello,

I was trying to run `python server.py --makeSampleConfig` and received the following error message:

`Traceback (most recent call last):
  File "server.py", line 16, in <module>
    from influxdbds import InfluxDBEntityContainer
  File "/test/odata-influxdb/influxdbds.py", line 9, in <module>
    from pyslet.odata2.core import EntityCollection, CommonExpression, PropertyExpression, BinaryExpression, \
ImportError: cannot import name FormatExpand`

It turns out that `FormatExpand` and `FormatSelect` were renamed in [pyslet.odata2.client](https://github.com/swl10/pyslet/commit/0ee9445d8db1c98d1d691520c5b1b41f822c25a7#diff-5b3660dfefc91875d09b5ce13c802661) to `format_expand` and `format_select`, respectively.

So, I changed the import on line 10 of `influxdbds.py` and the corresponding calls on line 389 and line 392.  Then, running `python server.py --makeSampleConfig` successfully created the `sample.conf` file.

Likewise, the `FormatSysQueryOptions` method was renamed in `pyslet.odata2.client` to `format_sys_query_options`.  So, I updated the call on line 405 of `influxdbds.py`.

Additionally, `from_DSN`  was renamed in `influxdb.client` to `from_dsn`.  So, updated the respective calls in `influxdbmeta.py` (line 57) and `influxdbds.py` (line 50).

**Comment by Jocoleqy** [comment]
Yeah, I did the same thing.  It works now but I don't know if those modifcations are correct. Waiting for the author's response.
